version: '3.3'
services:
   db:
     image: mariadb:10.2
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: db
       MYSQL_USER: root
       MYSQL_PASSWORD: root
     volumes:
       - db_data:/var/lib/mysql
     restart: always
   backend:
     depends_on:
       - db
     image: tfg-back
     ports:
       - "8001:5000"
     restart: always
     environment:
       MYSQL_HOST: db
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_DB: db
volumes:
    db_data: {}
